services:
  doorwatch:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - doorwatch-data:/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
      - DoorWatch__Camera__Source=Rtsp
      - DoorWatch__Camera__RtspUrl=${RTSP_URL}
      - DoorWatch__Detector__Method=EdgeBased
      - DoorWatch__Detector__Roi__X=932
      - DoorWatch__Detector__Roi__Y=80
      - DoorWatch__Detector__Roi__Width=900
      - DoorWatch__Detector__Roi__Height=250
      - DoorWatch__Detector__EdgeChangeThresholdPercent=18
      - DoorWatch__Detector__EdgeCloseThresholdPercent=10
      - DoorWatch__Detector__NightEdgeChangeThresholdPercent=9
      - DoorWatch__Detector__NightEdgeCloseThresholdPercent=7
      - DoorWatch__Detector__BaselineImagePath=/data/baseline.png
      - DoorWatch__HomeAssistant__BaseUrl=${HA_BASEURL}
      - DoorWatch__HomeAssistant__Token=${HA_TOKEN}
      - DoorWatch__HomeAssistant__EntityId=input_boolean.detected_door_state

volumes:
  doorwatch-data:
